[[redirects]]
  from = "https://silverithm.site/api/v1/*"
  to = "https://silverithm.netlify.app/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200