[[redirects]]
  from = "http://http://ec2-3-34-98-229.ap-northeast-2.compute.amazonaws.com:8080/api/v1/*"
  to = "https://silverithm.netlify.app/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200